springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: API de geracao de Nota Fiscal
    description: Esta API permite a geração da Nota Fiscal de pedidos.
    version: 1.0.0