version: '0.1'

services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: geradornotafiscal
    working_dir: /app
    entrypoint: >
      sh -c "
      apk add --no-cache curl &&
      curl -L -o app.jar https://github.com/vitoriasilva98/desafio-nota-fiscal/releases/download/v1.0.0/geradornotafiscal-1.0.0.jar &&
      java -jar app.jar
      "
    ports:
      - "8080:8080"