springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: API de geração de Nota Físcal
    description: Esta API permite a geração da Nota Físcal de pedidos.
    version: 1.0.0